server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/your-blog?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
  thymeleaf:
    mode: HTML
    cache: false
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true