server:
  port: 5187
spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/kiwi_blog?autoReconnect=true&serverTimezone=UTC
    #username: root
    #password: password
    url: jdbc:mysql://syh80882.cafe24.com/syh80882
    driverClassName: com.mysql.jdbc.Driver
    username: syh80882
    password: abc123!@
    sql-script-encoding: utf-8
  thymeleaf:
    mode: HTML
    cache: false
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

app:
  oauth:
    jwt:
      public-key: -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj1PhKA5qWltkVczEeYaF
        4rdOqppgWEGHKVKBRblJfTorEywumd/pIfWMrHQQWFQKsnTmshVZozKEvt3QKtnY
        DLdCqijdupIDgHHQ1dD7X/AnooJbsCm1uXDcPoGc1QH4S+xUskczns0aiGWFyeZ5
        28+mmS0OquA9wrxuT7qZd4OcdbNTk4t89kYMz1hTjXM7TL+gYQo1w1kswFFXOnSA
        ETVjyzHL+STsR5uyAFMHTI2zI7Y1Dr3IUceimH19IKoFG4V+ovJZ4YakRlB5OutH
        VfWovNnJh5x60Q1CcjRmp4u0onaJ2/Z3yf4t4lZHFy233Ttl7QajUaE1EDXy+Jqk
        nwIDAQAB
        -----END PUBLIC KEY-----

      expirationInMs: 604800000

environments:
  server-url: http://127.0.0.1